version: '3.9'

services:
  api:
    build: .
    container_name: audit-stream-api
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: audistream
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - db
    volumes:
    - ./prisma:/app/prisma

  db:
    image: postgres:16
    container_name: audi-stream-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: audistream
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
    db_data:
    pgadmin_data: